ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK1" CHECK (created_by is not null) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK2" CHECK (creation_date is not null) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK3" CHECK (last_updated_by is not null) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK4" CHECK (last_update_date is not null) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_PK" PRIMARY KEY ("GROUP_NAME", "OBJECT_NAME") ENABLE;

