whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on

prompt @@0001.TABLE.STD_OBJECTS.sql
@@0001.TABLE.STD_OBJECTS.sql
prompt @@0002.TYPE_SPEC.DBUG_CALL_OBJ_T.sql
@@0002.TYPE_SPEC.DBUG_CALL_OBJ_T.sql
prompt @@0003.TYPE_SPEC.DBUG_CALL_TAB_T.sql
@@0003.TYPE_SPEC.DBUG_CALL_TAB_T.sql
prompt @@0004.TYPE_SPEC.DBUG_LOG4PLSQL_OBJ_T.sql
@@0004.TYPE_SPEC.DBUG_LOG4PLSQL_OBJ_T.sql
prompt @@0005.TYPE_SPEC.DBUG_OBJ_T.sql
@@0005.TYPE_SPEC.DBUG_OBJ_T.sql
prompt @@0006.INDEX.STD_OBJECTS.sql
@@0006.INDEX.STD_OBJECTS.sql
prompt @@0007.CONSTRAINT.STD_OBJECTS.sql
@@0007.CONSTRAINT.STD_OBJECTS.sql
prompt @@0008.TYPE_SPEC.DBUG_PLSDBUG_OBJ_T.sql
@@0008.TYPE_SPEC.DBUG_PLSDBUG_OBJ_T.sql
prompt @@R__0009.PACKAGE_SPEC.DBUG.sql
@@R__0009.PACKAGE_SPEC.DBUG.sql
prompt @@R__0010.PACKAGE_SPEC.DBUG_TRIGGER.sql
@@R__0010.PACKAGE_SPEC.DBUG_TRIGGER.sql
prompt @@R__0011.PACKAGE_SPEC.DBUG_PROFILER.sql
@@R__0011.PACKAGE_SPEC.DBUG_PROFILER.sql
prompt @@R__0012.PACKAGE_SPEC.DBUG_LOG4PLSQL.sql
@@R__0012.PACKAGE_SPEC.DBUG_LOG4PLSQL.sql
prompt @@R__0013.PACKAGE_SPEC.DBUG_DBMS_OUTPUT.sql
@@R__0013.PACKAGE_SPEC.DBUG_DBMS_OUTPUT.sql
prompt @@R__0014.PACKAGE_SPEC.DBUG_DBMS_APPLICATION_INFO.sql
@@R__0014.PACKAGE_SPEC.DBUG_DBMS_APPLICATION_INFO.sql
prompt @@R__0015.PACKAGE_BODY.DBUG.sql
@@R__0015.PACKAGE_BODY.DBUG.sql
prompt @@R__0016.PACKAGE_BODY.DBUG_TRIGGER.sql
@@R__0016.PACKAGE_BODY.DBUG_TRIGGER.sql
prompt @@R__0017.PACKAGE_BODY.DBUG_PROFILER.sql
@@R__0017.PACKAGE_BODY.DBUG_PROFILER.sql
prompt @@R__0018.PACKAGE_BODY.DBUG_LOG4PLSQL.sql
@@R__0018.PACKAGE_BODY.DBUG_LOG4PLSQL.sql
prompt @@R__0019.PACKAGE_BODY.DBUG_DBMS_OUTPUT.sql
@@R__0019.PACKAGE_BODY.DBUG_DBMS_OUTPUT.sql
prompt @@R__0020.PACKAGE_BODY.DBUG_DBMS_APPLICATION_INFO.sql
@@R__0020.PACKAGE_BODY.DBUG_DBMS_APPLICATION_INFO.sql
prompt @@R__0021.TYPE_BODY.DBUG_PLSDBUG_OBJ_T.sql
@@R__0021.TYPE_BODY.DBUG_PLSDBUG_OBJ_T.sql
prompt @@R__0022.TYPE_BODY.DBUG_LOG4PLSQL_OBJ_T.sql
@@R__0022.TYPE_BODY.DBUG_LOG4PLSQL_OBJ_T.sql
prompt @@R__0023.TYPE_BODY.DBUG_OBJ_T.sql
@@R__0023.TYPE_BODY.DBUG_OBJ_T.sql
