whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on
ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

prompt 0001.TYPE_SPEC.DBUG_PLSDBUG_OBJ_T.sql
@@0001.TYPE_SPEC.DBUG_PLSDBUG_OBJ_T.sql
prompt R__0002.PACKAGE_SPEC.DBUG_PLSDBUG.sql
@@R__0002.PACKAGE_SPEC.DBUG_PLSDBUG.sql
prompt R__0003.PACKAGE_BODY.DBUG_PLSDBUG.sql
@@R__0003.PACKAGE_BODY.DBUG_PLSDBUG.sql
prompt R__0004.TYPE_BODY.DBUG_PLSDBUG_OBJ_T.sql
@@R__0004.TYPE_BODY.DBUG_PLSDBUG_OBJ_T.sql
prompt R__0005.PACKAGE_SPEC.PLSDBUG.sql
@@R__0005.PACKAGE_SPEC.PLSDBUG.sql
prompt R__0006.PACKAGE_BODY.PLSDBUG.sql
@@R__0006.PACKAGE_BODY.PLSDBUG.sql
